"""Tool-specific shim files generated by ``sensei init`` (ADR-0003)."""

from __future__ import annotations

from pathlib import Path

# Each shim points at AGENTS.md as the single source of truth.
SHIMS: dict[str, str] = {
    "CLAUDE.md": "See @AGENTS.md\n",
    ".kiro/steering/sensei.md": "# Sensei\n\nRead and follow the instructions in `AGENTS.md` at the instance root.\n",
    ".cursor/rules/sensei.mdc": (
        "---\ndescription: Sensei boot chain\nalwaysApply: true\n---\n"
        "Read and follow the instructions in `AGENTS.md` at the instance root.\n"
    ),
    ".github/copilot-instructions.md": "Read and follow the instructions in `AGENTS.md` at the instance root.\n",
    ".windsurf/rules/sensei.md": (
        "---\ntrigger: always_on\n---\n"
        "Read and follow the instructions in `AGENTS.md` at the instance root.\n"
    ),
    ".clinerules/sensei.md": "Read and follow the instructions in `AGENTS.md` at the instance root.\n",
    ".roo/rules/sensei.md": "Read and follow the instructions in `AGENTS.md` at the instance root.\n",
    ".aiassistant/rules/sensei.md": "Read and follow the instructions in `AGENTS.md` at the instance root.\n",
}


def write_shim(root: Path, rel_path: str, content: str) -> None:
    target = root / rel_path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
