"""Sensei CLI.

Subcommands:
    init <target>   Scaffold a Sensei instance at <target>.
    status          Report instance state.
    upgrade         Update .sensei/ to the installed package version.
    verify          Run validators.
"""

from __future__ import annotations

import os
import re
import shutil
import sys
from pathlib import Path

import click
import yaml

import sensei
from sensei import __version__

# Strict validation for --learner-id: letters, digits, underscore, hyphen;
# 1–64 characters. The value is interpolated into learner/profile.yaml and
# later embedded in LLM prompts, so we reject any character that could inject
# YAML, shell metacharacters, or prompt-steering content.
_LEARNER_ID_RE = re.compile(r"^[A-Za-z0-9_-]{1,64}$")

# Tool-specific shim files generated by `sensei init` (ADR-0003).
# Each shim points at AGENTS.md as the single source of truth.
_SHIMS: dict[str, str] = {
    "CLAUDE.md": "See @AGENTS.md\n",
    ".kiro/steering/sensei.md": "# Sensei\n\nRead and follow the instructions in `AGENTS.md` at the instance root.\n",
    ".cursor/rules/sensei.mdc": (
        "---\ndescription: Sensei boot chain\nalwaysApply: true\n---\n"
        "Read and follow the instructions in `AGENTS.md` at the instance root.\n"
    ),
    ".github/copilot-instructions.md": "Read and follow the instructions in `AGENTS.md` at the instance root.\n",
    ".windsurf/rules/sensei.md": (
        "---\ntrigger: always_on\n---\n"
        "Read and follow the instructions in `AGENTS.md` at the instance root.\n"
    ),
    ".clinerules/sensei.md": "Read and follow the instructions in `AGENTS.md` at the instance root.\n",
    ".roo/rules/sensei.md": "Read and follow the instructions in `AGENTS.md` at the instance root.\n",
    ".aiassistant/rules/sensei.md": "Read and follow the instructions in `AGENTS.md` at the instance root.\n",
}

_LEARNER_CONFIG_YAML = """# Learner-level overrides for Sensei defaults.
# Leave empty to use engine defaults from .sensei/defaults.yaml.
"""

_STARTER_PROFILE_HEADER = """\
# Sensei learner profile. See docs/specs/learner-profile.md for the contract.
# Validated by .sensei/scripts/check_profile.py.
"""


def _engine_source() -> Path:
    """Return a filesystem path to the bundled engine directory.

    The engine bundle is shipped inside the `sensei` package at `sensei/engine/`.
    It is not a Python subpackage (no __init__.py) — it is a data directory of
    markdown, yaml, and helper scripts that `sensei init` copies into `.sensei/`.
    """
    package_root = Path(sensei.__file__).parent
    engine_dir = package_root / "engine"
    if not engine_dir.is_dir():
        raise click.ClickException(f"Engine bundle not found at {engine_dir}")
    return engine_dir


def _fsync_dir(path: Path) -> None:
    """fsync *path* as a directory so recent rename dirents are durable.

    POSIX rename(2) only guarantees atomicity — not durability. Without an
    fsync on the containing directory, a power loss after rename() returns
    can lose the dirent update. No-op on non-POSIX.
    """
    if os.name != "posix":
        return
    fd = os.open(path, os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def _atomic_replace_engine(src: Path, sensei_dir: Path, version: str) -> None:
    """Install or replace `sensei_dir` with a fresh copy of `src`, atomically.

    Honors the per-upgrade atomicity contract documented in ADR-0004 and
    `docs/operations/release-playbook.md`: the learner's existing `.sensei/`
    is preserved across any failure of the copy step, and is recoverable
    after a crash during the short swap window.

    Algorithm (platform-agnostic, three-step swap):
      1. Copy the engine bundle to a sibling `.sensei.tmp/`.
      2. If `.sensei/` exists, rename it aside to `.sensei.old/`.
      3. Rename `.sensei.tmp/` into place as `.sensei/`.
      4. Remove `.sensei.old/`.

    Each rename is followed by _fsync_dir on the parent so the dirent update
    survives power loss.

    Crash recovery: if a previous run died between steps 2 and 3, the next
    call (or any subsequent `sensei` command that invokes this helper) sees
    `.sensei.old/` present and `.sensei/` missing, and restores the old.
    Leftover `.sensei.tmp/` from a prior failed copy is always cleaned first.
    """
    parent = sensei_dir.parent
    tmp_dir = parent / ".sensei.tmp"
    old_dir = parent / ".sensei.old"

    # Crash recovery from a prior interrupted swap.
    if old_dir.exists() and not sensei_dir.exists():
        old_dir.rename(sensei_dir)
        _fsync_dir(parent)
    elif old_dir.exists() and sensei_dir.exists():
        # Prior run completed the new install but died before cleanup.
        shutil.rmtree(old_dir)

    # Clean leftover temp from a prior failed copy.
    if tmp_dir.exists():
        shutil.rmtree(tmp_dir)

    # Step 1 — copy bundle to temp. Any failure here leaves `.sensei/` intact.
    try:
        shutil.copytree(src, tmp_dir)
        (tmp_dir / ".sensei-version").write_text(f"{version}\n", encoding="utf-8")
    except Exception:
        shutil.rmtree(tmp_dir, ignore_errors=True)
        raise

    # Steps 2–3 — swap aside + install new.
    swapped_aside = False
    try:
        if sensei_dir.exists():
            sensei_dir.rename(old_dir)
            _fsync_dir(parent)
            swapped_aside = True
        tmp_dir.rename(sensei_dir)
        _fsync_dir(parent)
    except Exception:
        # Best-effort rollback: put the old dir back if we moved it.
        if swapped_aside and old_dir.exists() and not sensei_dir.exists():
            old_dir.rename(sensei_dir)
            _fsync_dir(parent)
        shutil.rmtree(tmp_dir, ignore_errors=True)
        raise

    # Step 4 — remove the aside. `.sensei/` is now authoritative.
    if old_dir.exists():
        shutil.rmtree(old_dir, ignore_errors=True)


def _write_shim(root: Path, rel_path: str, content: str) -> None:
    target = root / rel_path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


@click.group()
@click.version_option(__version__, prog_name="sensei")
def main() -> None:
    """Sensei — pip-installable scaffolding for LLM-operated learning environments."""


@main.command()
@click.argument("target", type=click.Path(file_okay=False, path_type=Path))
@click.option("--force", is_flag=True, help="Overwrite an existing .sensei/ directory.")
@click.option(
    "--learner-id",
    default="learner",
    show_default=True,
    help="Identifier written to learner/profile.yaml. Edit later if you prefer a different name.",
)
def init(target: Path, force: bool, learner_id: str) -> None:
    """Scaffold a new Sensei instance at TARGET."""
    if not _LEARNER_ID_RE.match(learner_id):
        raise click.BadParameter(
            "must match ^[A-Za-z0-9_-]{1,64}$ (letters, digits, underscore, hyphen; 1–64 chars)",
            param_hint="--learner-id",
        )

    target = target.resolve()
    target.mkdir(parents=True, exist_ok=True)

    sensei_dir = target / ".sensei"
    if sensei_dir.exists() and not force:
        raise click.ClickException(
            f"Instance already exists at {sensei_dir}. "
            f"Run `sensei upgrade` to update the engine, or re-run with --force to reinitialize."
        )

    # Install engine bundle into .sensei/ atomically.
    _atomic_replace_engine(_engine_source(), sensei_dir, __version__)

    # Learner data directory + seed profile.
    (target / "learner").mkdir(exist_ok=True)
    (target / "learner" / "goals").mkdir(exist_ok=True)
    learner_config = target / "learner" / "config.yaml"
    if not learner_config.exists():
        learner_config.write_text(_LEARNER_CONFIG_YAML, encoding="utf-8")
    learner_profile = target / "learner" / "profile.yaml"
    if not learner_profile.exists():
        profile_body = yaml.safe_dump(
            {"schema_version": 0, "learner_id": learner_id, "expertise_map": {}},
            sort_keys=False,
        )
        learner_profile.write_text(
            _STARTER_PROFILE_HEADER + profile_body,
            encoding="utf-8",
        )

    # Hints ingestion directories and registry.
    (target / "learner" / "inbox").mkdir(exist_ok=True)
    (target / "learner" / "inbox" / ".gitkeep").write_text(
        "# Drop zone for raw learning hints (URLs, snippets, notes).\n", encoding="utf-8"
    )
    (target / "learner" / "hints" / "active").mkdir(parents=True, exist_ok=True)
    (target / "learner" / "hints" / "archive").mkdir(parents=True, exist_ok=True)
    hints_registry = target / "learner" / "hints" / "hints.yaml"
    if not hints_registry.exists():
        hints_registry.write_text("schema_version: 1\nhints: []\n", encoding="utf-8")

    # AGENTS.md + tool shims (ADR-0003). The boot document is bundled in the
    # engine (see src/sensei/engine/templates/AGENTS.md) rather than baked into
    # the CLI source, so it stays in sync with engine.md / protocols / schemas
    # any time the bundle is refreshed. `.sensei/` was just written above, so
    # the template is always readable from there.
    agents_template = sensei_dir / "templates" / "AGENTS.md"
    (target / "AGENTS.md").write_text(
        agents_template.read_text(encoding="utf-8"), encoding="utf-8"
    )
    for rel_path, content in _SHIMS.items():
        _write_shim(target, rel_path, content)

    click.echo(f"Created .sensei/ at {sensei_dir}")
    click.echo(f"Wrote AGENTS.md and {len(_SHIMS)} tool-specific shims.")
    click.echo(f"Seeded learner/profile.yaml with learner_id={learner_id!r}.")
    click.echo("Open this folder with any LLM agent to begin.")


@main.command()
@click.argument("target", type=click.Path(exists=True, file_okay=False, path_type=Path), default=".")
def status(target: Path) -> None:
    """Report instance state: engine version, profile summary, stale topics."""
    target = target.resolve()
    sensei_dir = target / ".sensei"
    if not sensei_dir.exists():
        raise click.ClickException(f"Not a Sensei instance: {target} (no .sensei/ directory).")

    version_file = sensei_dir / ".sensei-version"
    engine_version = version_file.read_text().strip() if version_file.exists() else "unknown"
    click.echo(f"Instance: {target}")
    click.echo(f"Engine:   {engine_version}")

    # Profile summary
    profile_path = target / "learner" / "profile.yaml"
    if not profile_path.exists():
        click.echo("Profile:  not found")
        return

    profile = yaml.safe_load(profile_path.read_text())
    if not isinstance(profile, dict):
        click.echo("Profile:  invalid (not a mapping)")
        return

    learner_id = profile.get("learner_id", "unknown")
    expertise = profile.get("expertise_map") or {}
    total = len(expertise)

    # Count by mastery level
    levels = {"mastered": 0, "solid": 0, "developing": 0, "shaky": 0, "none": 0}
    for topic_state in expertise.values():
        if isinstance(topic_state, dict):
            lvl = topic_state.get("mastery", "none")
            if lvl in levels:
                levels[lvl] += 1

    click.echo(f"Learner:  {learner_id}")
    click.echo(f"Topics:   {total}")

    if total > 0:
        parts = [f"{v} {k}" for k, v in levels.items() if v > 0]
        click.echo(f"Mastery:  {', '.join(parts)}")

        # Stale topics (due for review)
        from datetime import datetime, timezone

        from sensei.engine.scripts.decay import freshness_score

        now = datetime.now(tz=timezone.utc)
        defaults_path = sensei_dir / "defaults.yaml"
        defaults = yaml.safe_load(defaults_path.read_text()) if defaults_path.exists() else {}
        memory_cfg = defaults.get("memory", {}) if isinstance(defaults, dict) else {}
        half_life = float(memory_cfg.get("half_life_days", 7))
        threshold = float(memory_cfg.get("stale_threshold", 0.5))

        stale: list[str] = []
        malformed: list[str] = []
        for slug, state in expertise.items():
            if not isinstance(state, dict):
                continue
            last_seen_str = state.get("last_seen")
            if not last_seen_str:
                stale.append(slug)
                continue
            try:
                last_seen = datetime.fromisoformat(str(last_seen_str).replace("Z", "+00:00"))
                elapsed = (now - last_seen).total_seconds() / 86400.0
                if freshness_score(elapsed, half_life) < threshold:
                    stale.append(slug)
            except (ValueError, TypeError):
                # Treat as stale (conservative), but surface it so the learner
                # knows their profile has corrupt timestamps rather than a
                # silently-growing "due for review" list.
                stale.append(slug)
                malformed.append(slug)

        if malformed:
            click.echo(
                f"Warning:  {len(malformed)} topic{'s' if len(malformed) != 1 else ''} "
                f"with unparseable last_seen (treated as stale):"
            )
            for s in malformed[:5]:
                click.echo(f"          - {s}")
            if len(malformed) > 5:
                click.echo(f"          ... and {len(malformed) - 5} more")

        if stale:
            click.echo(f"Stale:    {len(stale)} topic{'s' if len(stale) != 1 else ''} due for review")
            for s in stale[:5]:
                click.echo(f"          - {s}")
            if len(stale) > 5:
                click.echo(f"          ... and {len(stale) - 5} more")


@main.command()
@click.argument("target", type=click.Path(exists=True, file_okay=False, path_type=Path), default=".")
def upgrade(target: Path) -> None:
    """Update .sensei/ engine bundle to the installed package version."""
    target = target.resolve()
    sensei_dir = target / ".sensei"
    if not sensei_dir.exists():
        raise click.ClickException(f"Not a Sensei instance: {target} (no .sensei/ directory).")

    # Read current version
    version_file = sensei_dir / ".sensei-version"
    old_version = version_file.read_text().strip() if version_file.exists() else "unknown"

    if old_version == __version__:
        click.echo(f"Already at {__version__}. Nothing to upgrade.")
        return

    # Migrate learner state files BEFORE swapping the engine. If migration
    # fails (bad YAML, permissions, failed schema transform), the existing
    # engine remains on disk and is still compatible with the unmigrated
    # data. Swapping first would leave a new engine paired with old-format
    # data if a subsequent migration failed.
    learner_dir = target / "learner"
    migrated: list[str] = []
    if learner_dir.exists():
        from sensei.engine.scripts.migrate import migrate_instance

        migrated = migrate_instance(learner_dir)

    # Replace engine bundle atomically (learner/ is untouched).
    _atomic_replace_engine(_engine_source(), sensei_dir, __version__)

    click.echo(f"Upgraded .sensei/ from {old_version} → {__version__}")
    if learner_dir.exists():
        if migrated:
            for desc in migrated:
                click.echo(f"  Migrated: {desc}")
        else:
            click.echo("  Instance schemas already current.")
    click.echo("Learner data (learner/) preserved.")


@main.command()
@click.argument("target", type=click.Path(exists=True, file_okay=False, path_type=Path), default=".")
def verify(target: Path) -> None:
    """Verify engine bundle integrity: expected files present, profile valid."""
    target = target.resolve()
    sensei_dir = target / ".sensei"
    if not sensei_dir.exists():
        raise click.ClickException(f"Not a Sensei instance: {target} (no .sensei/ directory).")

    errors: list[str] = []

    expected = [
        "engine.md",
        "defaults.yaml",
        ".sensei-version",
        "scripts/config.py",
        "scripts/check_profile.py",
        "scripts/classify_confidence.py",
        "scripts/decay.py",
        "scripts/mastery_check.py",
        "scripts/check_goal.py",
        "protocols/review.md",
        "protocols/assess.md",
        "protocols/goal.md",
        "protocols/personality.md",
        "protocols/modes/tutor.md",
        "protocols/modes/assessor.md",
        "protocols/modes/challenger.md",
        "protocols/modes/reviewer.md",
        "schemas/profile.schema.json",
        "templates/AGENTS.md",
    ]
    for rel in expected:
        if not (sensei_dir / rel).exists():
            errors.append(f"missing: .sensei/{rel}")

    profile_path = target / "learner" / "profile.yaml"
    if profile_path.exists():
        try:
            profile = yaml.safe_load(profile_path.read_text())
            if isinstance(profile, dict):
                from sensei.engine.scripts.check_profile import validate_profile

                v_status, errs = validate_profile(profile)
                if v_status != "ok":
                    for e in errs:
                        errors.append(f"profile: {e}")
            else:
                errors.append("profile: not a YAML mapping")
        except yaml.YAMLError as exc:
            errors.append(f"profile: invalid YAML — {exc}")
    else:
        errors.append("missing: learner/profile.yaml")

    if errors:
        click.echo("FAIL")
        for e in errors:
            click.echo(f"  ✗ {e}")
        sys.exit(1)
    else:
        click.echo("OK — engine bundle intact, profile valid.")


if __name__ == "__main__":
    main()
