"""Sensei CLI.

Subcommands:
    init <target>   Scaffold a Sensei instance at <target>.
    status          Report instance state (stub).
    upgrade         Update .sensei/ to the installed package version (stub).
    verify          Run validators (stub).
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path
from string import Template

import click

import sensei
from sensei import __version__

# Tool-specific shim files generated by `sensei init` (ADR-0003).
# Each shim points at AGENTS.md as the single source of truth.
_SHIMS: dict[str, str] = {
    "CLAUDE.md": "See @AGENTS.md\n",
    ".kiro/steering/sensei.md": "# Sensei\n\nRead and follow the instructions in `AGENTS.md` at the instance root.\n",
    ".cursor/rules/sensei.mdc": (
        "---\ndescription: Sensei boot chain\nalwaysApply: true\n---\n"
        "Read and follow the instructions in `AGENTS.md` at the instance root.\n"
    ),
    ".github/copilot-instructions.md": "Read and follow the instructions in `AGENTS.md` at the instance root.\n",
    ".windsurf/rules/sensei.md": (
        "---\ntrigger: always_on\n---\n"
        "Read and follow the instructions in `AGENTS.md` at the instance root.\n"
    ),
    ".clinerules/sensei.md": "Read and follow the instructions in `AGENTS.md` at the instance root.\n",
    ".roo/rules/sensei.md": "Read and follow the instructions in `AGENTS.md` at the instance root.\n",
    ".aiassistant/rules/sensei.md": "Read and follow the instructions in `AGENTS.md` at the instance root.\n",
}

_AGENTS_MD = """# AGENTS.md — Sensei Boot Document

You are operating a Sensei learning-environment instance. Follow the boot chain below.

## Boot Chain

1. Read `.sensei/engine.md` — the kernel. It defines the dispatch table and invariants.
2. Dispatch to `.sensei/protocols/<name>.md` based on the user's intent.
3. Read `.sensei/defaults.yaml` for tunables and `instance/config.yaml` for overrides.
4. Consult `instance/profile.yaml` and other state files before making pedagogical decisions.

## Key Constraints

- Never teach during assessment (ADR forthcoming — mentor behavioral invariants).
- After two failed attempts at the same concept, diagnose prerequisites before a third explanation.
- Silence is a first-class action. Short responses are the default; long responses are the exception.

## References

- `.sensei/engine.md` — kernel and dispatch table
- `.sensei/README.md` — engine contents overview (if present)
"""

_INSTANCE_CONFIG_YAML = """# Instance-level overrides for Sensei defaults.
# Leave empty to use engine defaults from .sensei/defaults.yaml.
"""

_STARTER_PROFILE_YAML = """\
# Sensei learner profile. See docs/specs/learner-profile.md for the contract.
# Validated by .sensei/scripts/check_profile.py.
schema_version: 0
learner_id: $learner_id
expertise_map: {}
"""


def _engine_source() -> Path:
    """Return a filesystem path to the bundled engine directory.

    The engine bundle is shipped inside the `sensei` package at `sensei/engine/`.
    It is not a Python subpackage (no __init__.py) — it is a data directory of
    markdown, yaml, and helper scripts that `sensei init` copies into `.sensei/`.
    """
    package_root = Path(sensei.__file__).parent
    engine_dir = package_root / "engine"
    if not engine_dir.is_dir():
        raise click.ClickException(f"Engine bundle not found at {engine_dir}")
    return engine_dir


def _write_shim(root: Path, rel_path: str, content: str) -> None:
    target = root / rel_path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


@click.group()
@click.version_option(__version__, prog_name="sensei")
def main() -> None:
    """Sensei — pip-installable scaffolding for LLM-operated learning environments."""


@main.command()
@click.argument("target", type=click.Path(file_okay=False, path_type=Path))
@click.option("--force", is_flag=True, help="Overwrite an existing .sensei/ directory.")
@click.option(
    "--learner-id",
    default="learner",
    show_default=True,
    help="Identifier written to instance/profile.yaml. Edit later if you prefer a different name.",
)
def init(target: Path, force: bool, learner_id: str) -> None:
    """Scaffold a new Sensei instance at TARGET."""
    target = target.resolve()
    target.mkdir(parents=True, exist_ok=True)

    sensei_dir = target / ".sensei"
    if sensei_dir.exists() and not force:
        raise click.ClickException(
            f"Instance already exists at {sensei_dir}. "
            f"Run `sensei upgrade` to update the engine, or re-run with --force to reinitialize."
        )
    if sensei_dir.exists() and force:
        shutil.rmtree(sensei_dir)

    # Copy the engine bundle into .sensei/.
    shutil.copytree(_engine_source(), sensei_dir)
    (sensei_dir / ".sensei-version").write_text(f"{__version__}\n", encoding="utf-8")

    # Instance config directory + seed profile.
    (target / "instance").mkdir(exist_ok=True)
    instance_config = target / "instance" / "config.yaml"
    if not instance_config.exists():
        instance_config.write_text(_INSTANCE_CONFIG_YAML, encoding="utf-8")
    instance_profile = target / "instance" / "profile.yaml"
    if not instance_profile.exists():
        instance_profile.write_text(
            Template(_STARTER_PROFILE_YAML).substitute(learner_id=learner_id),
            encoding="utf-8",
        )

    # AGENTS.md + tool shims (ADR-0003).
    (target / "AGENTS.md").write_text(_AGENTS_MD, encoding="utf-8")
    for rel_path, content in _SHIMS.items():
        _write_shim(target, rel_path, content)

    click.echo(f"Created .sensei/ at {sensei_dir}")
    click.echo(f"Wrote AGENTS.md and {len(_SHIMS)} tool-specific shims.")
    click.echo(f"Seeded instance/profile.yaml with learner_id={learner_id!r}.")
    click.echo("Open this folder with any LLM agent to begin.")


@main.command()
@click.argument("target", type=click.Path(exists=True, file_okay=False, path_type=Path), default=".")
def status(target: Path) -> None:
    """Report instance state (stub)."""
    target = target.resolve()
    sensei_dir = target / ".sensei"
    if not sensei_dir.exists():
        raise click.ClickException(f"Not a Sensei instance: {target} (no .sensei/ directory).")
    version_file = sensei_dir / ".sensei-version"
    engine_version = version_file.read_text().strip() if version_file.exists() else "unknown"
    click.echo(f"Instance: {target}")
    click.echo(f"Engine version: {engine_version}")
    click.echo("Status: ok (stub — learner/goal reporting not yet implemented)")


@main.command()
def upgrade() -> None:
    """Update .sensei/ to the installed package version (stub)."""
    click.echo("upgrade: not yet implemented")
    sys.exit(2)


@main.command()
def verify() -> None:
    """Run validators (stub)."""
    click.echo("verify: no validators yet")
    sys.exit(0)


if __name__ == "__main__":
    main()
