kit_version: 0.2.0a11
aspects:
  kanon-fidelity:
    depth: 1
    enabled_at: '2026-04-28T21:14:44+00:00'
    config: {}
  kanon-sdd:
    depth: 3
    enabled_at: '2026-04-28T21:14:44+00:00'
    config: {}
  kanon-worktrees:
    depth: 2
    enabled_at: '2026-04-28T21:14:44+00:00'
    config: {}
  kanon-release:
    depth: 2
    enabled_at: '2026-04-28T21:14:44+00:00'
    config: {}
  kanon-testing:
    depth: 3
    enabled_at: '2026-04-28T21:14:44+00:00'
    config: {}
  kanon-security:
    depth: 2
    enabled_at: '2026-04-28T21:14:44+00:00'
    config: {}
  kanon-deps:
    depth: 2
    enabled_at: '2026-04-28T21:14:44+00:00'
    config: {}
  project-foundations:
    depth: 1
    enabled_at: '2026-04-28T21:14:44+00:00'
    config: {}
  project-release:
    depth: 1
    enabled_at: '2026-04-28T21:14:44+00:00'
    config: {}
